# 1. gpu devices
accelerator: null
gpus: "0"
amp_backend: native

# 2. train setting
check_val_every_n_epoch: 1
val_check_interval: 1.0
max_epochs: null

# 3. logger & callbacks
logger: true
log_every_n_steps: 50
callbacks: null
checkpoint_callback: true
resume_from_checkpoint: null

# 4. hyper param tuning
auto_lr_find: false
auto_scale_batch_size: false

# 4. for debugging
fast_dev_run: false
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
limit_predict_batches: 1.0

# 5. etc
profiler: null
precision: 32
multiple_trainloader_mode: max_size_cycle

